# Generated by Django 5.0.4 on 2024-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_photo_alter_employee_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
